name: Nx Distributed Tasks
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --no-tags --prune --depth=1 origin main
      - run: yarn install
      - run: yarn nx affected --target=test --base=main --head=HEAD
      - run: yarn nx affected --target=lint --base=main --head=HEAD
      - run: yarn nx affected --target=build --base=main --head=HEAD --prod
